config/routes.rb
DagingeHomeRails::Application.routes.draw do
  resources :resources

  resources :volunteer_jobs

  resources :educations

  resources :jobs

  resources :users

  post "users" => "user#create"
  
  get "users/edit/:id" => "user#edit"

  put "user/:id" => "user#update"

  get "user/new"

  get "sessions/login"

  post "sessions/authenticate"

  get "sessions/destroy"

  get "home/index"
  root :to => 'home#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  load_and_authorize_resource
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :ok }
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job, :html => { :class => "yform columnar" }) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation" class="error">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% @job.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <legend><%= t('common') %></legend>
    <div class="type-text_field">
      <%= f.label :employer %><br />
      <%= f.text_field :employer %>
    </div>
    <div class="type-text_field">
      <%= f.label :homepage %><br />
      <%= f.text_field :homepage %>
    </div>
    <div class="type-date_select">
      <%= f.label :from %><br />
      <%= f.date_select :from %>
    </div>
    <div class="type-date_select">
      <%= f.label :to %><br />
      <%= f.date_select :to %>
      <%= f.label :still_employed %>
      <%= f.check_box :still_employed %>
    </div>
  </fieldset>
  <fieldset>
    <legend>Norwegian</legend>
    <div class="type-text_field">
      <%= f.label :title_no %><br />
      <%= f.text_field :title_no %>
    </div>
    <div class="type-text_area">
      <%= f.label :description_no %><br />
      <%= f.text_area :description_no %>
    </div>
  </fieldset>
  <fieldset>
    <legend>English</legend>
    <div class="type-text_field">
      <%= f.label :title_en %><br />
      <%= f.text_field :title_en %>
    </div>
    <div class="type-text_area">
      <%= f.label :description_en %><br />
      <%= f.text_area :description_en %>
    </div>
  </fieldset>
  <%= f.submit :class => "submit" %>
<% end %>

app/views/jobs/edit.html.erb
<div class="action-menu">
<%= link_to 'Show', @job, confirm: 'This will cancel all changes. Are you sure?', method: :get, :class => :button %>
<%= link_to 'Back', jobs_path, confirm: 'This will cancel all changes. Are you sure?', method: :get, :class => :button  %>
</div>
<h1>Editing job</h1>

<%= render 'form' %>

app/views/jobs/index.html.erb
<div class="action-menu">
  <%= link_to 'New Job', new_job_path, :class => "big button" %>
</div>
<h1>Jobs</h1>
<% @jobs.each do |job| %>
  <div id="item<%= job.id %>" class="item">
    <div class="action-menu">
      <%= link_to "Show", job, :class => "primary button" %>
      <%= link_to 'Edit', edit_job_path(job), :class => "button" %>
      <%= link_to 'Destroy', job, :id => "delete"+ job.id.to_s, confirm: 'Are you sure?', method: :delete, :class => " delete negative button" %>
    </div>

    <h6><%= job.employer %> <%= link_to image_tag("icons/house_link.png", :alt => "Homepage"), job.homepage %></h6>
    <p><%= job.from %> - <%= job.still_employed ? "Now":job.to.strftime("%b %Y") %><br><%= job.title_en %></p>
  </div>
<% end %>
</table>

app/views/jobs/new.html.erb
<div class="action-menu">
<%= link_to 'Back', jobs_path, :class => "button", confirm: 'This will cancel all changes. Are you sure?', method: :get  %>
</div>
<h1>New job</h1>

<%= render 'form' %>

app/views/jobs/show.html.erb
<h1><%= @job.employer %> - <%= @job.title_en %></h1>
<div class="action-menu">
  <%= link_to 'Edit', edit_job_path(@job), :class => "button" %>
  <%= link_to 'Back', jobs_path, :class => "button" %>
</div>

<p class="quiet"><%= link_to @job.homepage, @job.homepage %><br><%= @job.from %> - <%= @job.to %></p>

<p>
<p>
<h6>Description:</h6>
<p>
<%= @job.description_en %>
</p>