config/routes.rb
DagingeHomeRails::Application.routes.draw do
  resources :resources

  resources :volunteer_jobs

  resources :educations

  resources :jobs

  resources :users

  post "users" => "user#create"
  
  get "users/edit/:id" => "user#edit"

  put "user/:id" => "user#update"

  get "user/new"

  get "sessions/login"

  post "sessions/authenticate"

  get "sessions/destroy"

  get "home/index"
  root :to => 'home#index'

end

app/views/resources/_form.html.erb
<%= form_for(@resource, :html => { :class => "yform columnar" }) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation" class="error">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
        <% @resource.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <legend>Resource</legend>
    <div class="type-text_field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="type-text_field">
      <%= f.label :link %><br />
      <%= f.text_field :link %>
    </div>
    <div class="type-text_field">
      <%= f.label :description_en %><br />
      <%= f.text_field :description_en %>
    </div>
    <div class="type-text_field">
      <%= f.label :description_no %><br />
      <%= f.text_field :description_no %>
    </div>
  </fieldset>
  <div class="type-button">
    <%= f.submit :class => "submit" %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<div class="action-menu">
  <%= link_to 'Show', @resource, confirm: 'This will cancel all changes. Are you sure?', method: :get, :class => "button" %>
  <%= link_to 'Back', resources_path, confirm: 'This will cancel all changes. Are you sure?', method: :get , :class => "button" %>
</div>
<h1>Editing resource</h1>

<%= render 'form' %>

app/views/resources/index.html.erb
<div class="action-menu">
  <%= link_to 'New Resource', new_resource_path, :class => "plus big button"%>
</div>
<h1>Resources</h1>
<% @resources.each do |resource| %>
  <div id="item<%= resource.id %>" class="item">
    <div class="action-menu">
      <%= link_to 'Show', resource, :class => "primary button" %></td>
      <%= link_to 'Edit', edit_resource_path(resource), :class => "pen button" %></td>
      <%= link_to 'Destroy', resource, confirm: 'Are you sure?', method: :delete, :class => "cross negative button" %></td>
    </div> 
    <h6><%= link_to resource.title, resource.link %></h6>
    <p><%= resource.description_en %></p>
  </div>
<% end %>
</table>

app/views/resources/new.html.erb
<div class="action-menu">
<%= link_to 'Back', resources_path, confirm: 'This will cancel all changes. Are you sure?', method: :get, :class => "button"  %>
</div>
<h1>New resource</h1>

<%= render 'form' %>

app/views/resources/show.html.erb
<div class="action-menu">
<%= link_to 'Edit', edit_resource_path(@resource), :class => "button" %>
<%= link_to 'Back', resources_path, :class => "button" %>
</div>
  <p>
  <b>Title:</b>
  <%= @resource.title %>
  </p>

  <p>
  <b>Link:</b>
  <%= @resource.link %>
  </p>

  <p>
  <b>Description:</b>
  <%= @resource.description_en %>
  </p>