config/routes.rb
DagingeHomeRails::Application.routes.draw do
  resources :resources

  resources :volunteer_jobs

  resources :educations

  resources :jobs

  resources :users

  post "users" => "user#create"
  
  get "users/edit/:id" => "user#edit"

  put "user/:id" => "user#update"

  get "user/new"

  get "sessions/login"

  post "sessions/authenticate"

  get "sessions/destroy"

  get "home/index"
  root :to => 'home#index'

end

app/models/education.rb
class Education < ActiveRecord::Base
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  load_and_authorize_resource
  # GET /educations
  # GET /educations.json
  def index
    @educations = Education.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @educations }
    end
  end

  # GET /educations/1
  # GET /educations/1.json
  def show
    @education = Education.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @education }
    end
  end

  # GET /educations/new
  # GET /educations/new.json
  def new
    @education = Education.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @education }
    end
  end

  # GET /educations/1/edit
  def edit
    @education = Education.find(params[:id])
  end

  # POST /educations
  # POST /educations.json
  def create
    @education = Education.new(params[:education])

    respond_to do |format|
      if @education.save
        format.html { redirect_to @education, notice: 'Education was successfully created.' }
        format.json { render json: @education, status: :created, location: @education }
      else
        format.html { render action: "new" }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /educations/1
  # PUT /educations/1.json
  def update
    @education = Education.find(params[:id])

    respond_to do |format|
      if @education.update_attributes(params[:education])
        format.html { redirect_to @education, notice: 'Education was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1
  # DELETE /educations/1.json
  def destroy
    @education = Education.find(params[:id])
    @education.destroy

    respond_to do |format|
      format.html { redirect_to educations_url }
      format.json { head :ok }
    end
  end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/_form.html.erb
<%= form_for(@education, :html => { :class => "yform columnar" }) do |f| %>
  <% if @education.errors.any? %>
    <div id="error_explanation" class="error">
      <h2><%= pluralize(@education.errors.count, "error") %> prohibited this education from being saved:</h2>

      <ul>
        <% @education.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <legend>Common</legend>
    <div class="type-text_field">
      <%= f.label :school %><br />
      <%= f.text_field :school %>
    </div>
    <div class="type-text_field">
      <%= f.label :homepage %><br />
      <%= f.text_field :homepage %>
    </div>
    <div class="type-date_select">
      <%= f.label :from %><br />
      <%= f.date_select :from %>
    </div>
    <div class="type-date_select">
      <%= f.label :to %><br />
      <%= f.date_select :to %>
      <%= f.label :still_student %>
      <%= f.check_box :still_student %>
    </div>
  </fieldset>
  <fieldset>
    <legend>Norwegian</legend>
    <div class="type-text_field">
      <%= f.label :degree_no %><br />
      <%= f.text_field :degree_no %>
    </div>
    <div class="type-text_area">
      <%= f.label :description_no %><br />
      <%= f.text_area :description_no %>
    </div>
  </fieldset>
  <fieldset>
    <legend>English</legend>
    <div class="type-text_field">
      <%= f.label :degree_en %><br />
      <%= f.text_field :degree_en %>
    </div>
    <div class="type-text_area">
      <%= f.label :description_en %><br />
      <%= f.text_area :description_en %>
    </div>
  </fieldset>
  <div class="type-button">
    <%= f.submit :class => "submit" %>
  </div>
<% end %>

app/views/educations/edit.html.erb
<div class="action-menu">
  <%= link_to 'Show', @education, confirm: 'This will cancel all changes. Are you sure?', method: :get, :class => "button" %>
  <%= link_to 'Back', educations_path, confirm: 'This will cancel all changes. Are you sure?', method: :get , :class => "button" %>
</div>
<h1>Editing education</h1>

<%= render 'form' %>

app/views/educations/index.html.erb
<div class="action-menu">
  <%= link_to 'New Education', new_education_path, :class => "plus big button"%>
</div>
<h1>Educations</h1>
<% @educations.each do |education| %>

  <div class="item">
    <div class="action-menu">
      <%= link_to 'Show', education, :class => "primary button" %>
      <%= link_to 'Edit', edit_education_path(education), :class => "pen button" %>
      <%= link_to 'Destroy', education, confirm: 'Are you sure?', method: :delete, :class => "cross negative button" %>
    </div>
    <h6><%= education.school %> <%= link_to image_tag("icons/house_link.png", :alt => "Homepage"), education.homepage %></h6>
    <p><%= education.from %> - <%= education.still_student ? "Now":education.to %><br><%= education.degree_en %></p>
  </div>
<% end %>

app/views/educations/new.html.erb
<div class="action-menu">
<%= link_to 'Back', educations_path, confirm: 'This will cancel all changes. Are you sure?', method: :get, :class => "button"  %>
</div>
<h1>New education</h1>

<%= render 'form' %>

app/views/educations/show.html.erb
<div class="action-menu">
<%= link_to 'Edit', edit_education_path(@education), :class => "button" %>
<%= link_to 'Back', educations_path, :class => "button" %>
</div>
<h6><%= @education.school %> - <%= @education.degree_en %></h6>
  <p>
  <b>Homepage:</b>
  <%= @education.homepage %>
  </p>

  <p>
  <b>From:</b>
  <%= @education.from %>
  </p>

  <p>
  <b>To:</b>
  <%= @education.to %>
  </p>

  <p>
  <b>Still student:</b>
  <%= @education.still_student %>
  </p>

  <p>
  <b>Degree no:</b>
  <%= @education.degree_no %>
  </p>

  <p>
  <b>Description no:</b>
  <%= @education.description_no %>
  </p>

  <p>
  <b>Degree en:</b>
  <%= @education.degree_en %>
  </p>

  <p>
  <b>Description en:</b>
  <%= @education.description_en %>
  </p>