config/routes.rb
DagingeHomeRails::Application.routes.draw do
  resources :resources

  resources :volunteer_jobs

  resources :educations

  resources :jobs

  resources :users

  post "users" => "user#create"
  
  get "users/edit/:id" => "user#edit"

  put "user/:id" => "user#update"

  get "user/new"

  get "sessions/login"

  post "sessions/authenticate"

  get "sessions/destroy"

  get "home/index"
  root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>daginge.com</title>
    <meta name="viewport" content="width=950, initial-scale=1">
    <meta charset="utf-8" />
    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
   </head>
   <body>
     <header>
     <h1 id="header">daginge.com</h1>
     <ul>
       <li><a href="/">Information</a></li>
       <% if current_user and current_user.admin? %>
         <li><%= link_to 'Me', edit_user_path(current_user) %></li>
         <li><%= link_to 'Job', jobs_path %></li>
         <li><%= link_to 'Education', educations_path %></li>
         <li><%= link_to 'Volunteer', volunteer_jobs_path %></li>
         <li><%= link_to 'Resources', resources_path %></li>
       <% end %>
       <li><a id="whereami" href="#where_am_i">Where am I?</a></li>
     </ul>
     <div class="action-menu">
       <% unless current_user %>
         <%= link_to 'Login', sessions_login_path, :class => "button" %>
       <% else %>
         <%= link_to 'Log out', sessions_destroy_path, :class => "button" %>
       <% end %>
     </div>
     </header>


     <div class="container top">
       <div class="span-24">
         <% if notice %>
           <p class="success"><%= image_tag('icons/accept.png', width: "16px", height: "16px", alt: "accept") %> <%= notice %></p>
         <% end %>
         <% if alert %>
           <p class="error"><%= alert %></p>
         <% end %>
       </div>
       <div class="span-16">
         <div class="post">
           <%= yield %>
         </div>
       </div>
       <div class="span-8 last">
         <div id="position" class="hide widget">
           <h1>You are here ↓</h1> 
         </div>
         <%= yield :sidebar %>
         <div class="widget">
           <h1><%= t("generic.contact") %></h1>
           <p>You can contact me by checking out my <a href="http://www.facebook.com/dagingeaas">Facebook</a>, <a href="http://www.twitter.com/daginge">Twitter</a> or <a href="http://www.linkedin.com/pub/dag-inge-aas/19/76b/294">LinkedIn</a> profile or by sending me an email to daginge [at] gmail.com.</p>
           <p>You can also reach me at my university address: dagingaa [at] stud.ntnu.no</p>
         </div>

       </div>
       <footer class="span-24">
       <p class="quiet">Page built by Dag-Inge Aas using HTML5, CSS3, Compass, Blueprint, SASS and jQuery. Special thanks to famfamfam for Silk Icons and fontsquirrel for custom font. Design and colors by Dag-Inge Aas. Validates <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fdaginge.com%2F">HTML5</a>. This project on <a href="https://github.com/dagingaa/daginge-home-rails">GitHub</a>.</p>
       </footer>
     </body>
   </html>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js" type="text/javascript"></script>
    <%= javascript_include_tag "application" %>
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-7814313-1']);
      _gaq.push(['_trackPageview']);

      (function() {
       var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
       ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
       var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
       })();

</script>